# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealname', models.CharField(max_length=50)),
                ('mealdesc', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField()),
                ('date_available', models.DateTimeField()),
                ('servings_available', models.IntegerField()),
                ('meal_rating', models.IntegerField(choices=[(0, 'No Stars'), (1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Starts')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MealRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealRequestName', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('date_requested', models.DateTimeField()),
                ('servings_requested', models.IntegerField()),
                ('other', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@someEmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('C', 'Chef'), ('M', 'Mouth')], max_length=1),
        ),
        migrations.AddField(
            model_name='mealrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Meal'),
        ),
    ]
