# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170309_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 17, 5, 53, 16147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 17, 5, 53, 16177, tzinfo=utc)),
        ),
    ]
