# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170309_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
