# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170312_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_rating',
            field=models.IntegerField(choices=[(0, 'No Stars'), (1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=0),
        ),
    ]
