# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20170323_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date_available',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, default='meals/None/noimg.jpg', upload_to='meals/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='servings_available',
            field=models.IntegerField(null=True),
        ),
    ]
