# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='meal_rating',
            field=models.IntegerField(choices=[(0, 'No Stars'), (1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, default='meals/None/noimg.jpg', upload_to='meals/%Y/%m/%d'),
        ),
    ]
