# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0004_auto_20170406_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
