# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0005_auto_20170406_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrequest',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='meal',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
