# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0008_auto_20170407_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date_available',
        ),
    ]
