# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0009_remove_meal_date_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_rating',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealdesc',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, default='meals/None/chef_hat.jpg', upload_to='meals/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=0),
        ),
    ]
