# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0010_auto_20170412_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrequest',
            name='requested_time',
            field=models.DateTimeField(null=True),
        ),
    ]
