# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0011_auto_20170425_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
