# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0011_mealrequest_requested_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrequest',
            name='requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='requested_time',
            field=models.TimeField(null=True),
        ),
    ]
