# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0012_auto_20170425_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
