# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealhub', '0013_auto_20170425_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date_available',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
